---
title: "CV"
author: "Michael Schramm"
email: mpschramm@gmail.com
output:
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
geometry: margin=1in
linkcolor: blue
github: mps9506
fontawesome: yes
phone: 910 232-3760
address: 578 John Kimbrough Blvd · 2260 TAMU · College Station, TX 77843
updated: no
urlcolor: blue
---


# Employment

*Texas Water Resources Institute, Texas A&M AgriLife Research and Extension Service*

Research Specialist III \hfill 2019-current  
Research Associate \hfill 2016-2019

*Oak Ridge National Laboratory, Oak Ridge, TN*

Research Associate \hfill 2014-2016

*Center for Energy and Environmental Policy, University of Delaware*

Research Assistant \hfill 2012-2013

# Education

*University of Delaware*, Master of Energy and Environmental Policy, 2013

*University of North Carolina - Wilmington*, B.A. Environmetal Studies, 2011

*University of North Carolina - Wilmington*, B.S. Biology, 2004

# Skills

Data Analysis, Environmental Policy, GIS, Grant Writing, Policy Analysis, `Python`, `R`, Reproducible Research, Stakeholder Facilitation, Technical Writing, Water Quality Modeling and Assessment, Watershed Planning

# Publications

## Journal Articles

**Schramm, M.P.**, Bevelhimer, M.S., Scherelis, C. 2017. Effects of hydrokinetic turbine sound on the behavior of four species of fish within an experimental mesocosm. *Fisheries Research* 190:1-14. doi:10.1016/j.fishres.2017.01.012

DeRolph, C.R., **Schramm, M.P.**, Bevelhimer, M.S. 2016. Predicting environmental mitigation requirements for hydropower projects through the integration of biophysical and socio-political geographies. *Science of The Total Environment* 566:888-918. doi:10.1016/j.scitotenv.2016.05.099

**Schramm, M.P.**, Bevelhimer, M.P., DeRolph, C.R. 2016. A synthesis of environmental and recreational mitigation requirements at hydropower projects in the United States. *Environmental Science & Policy* 61:87-96. doi:10.1016/j.envsci.2016.03.019

Pracheil, B.M., DeRolph C.R., **Schramm, M.P.**, Bevelhimer, M.S. 2016. A fish-eye view of riverine hydropower systems: the current understanding of the biological response to turbine passage. *Reviews in Fish Biology and Fisheries* 26(2):153-167. doi:10.1007/s11160-015-9416-8

Cutting, R.H., Cahoon, L.B., Flood, J.F., Horton, L., **Schramm, M.P.** 2010. Spill the beans: GoodGuide, Walmart and EPA use information as efficient, market-based environmental regulation. *Tul. Envtl. LJ* 24:291.

## Other Publications

Jain, S., Ruff, S., **Schramm, M.** 2018. Technical Support Document for One Total Maximum Daily Load for Indicator Bacteria in Arenosa Creek. Prepared by the Texas Water Resources Institute for the Total Maximum Daily Load Program, Texas Commission on Environmental Quality. Austin, TX. URL: https://www.tceq.texas.gov/assets/public/waterquality/tmdl/108arenosa/108-arenosa-tsd-final.pdf

**Schramm, M.P.**, Broad, T., Arsuffi, R. 2018. *Escherichia coli* and Dissolved Oxygen Trends in the Upper Llano River Watershed, Texas (2001-2016). Technical Report, Texas Water Resources Institute TR-511. Prepared by the Texas Water Resources Institute and Llano River Field Station for the Texas State Soil and Water Conservation Board. Temple, TX. URL: http://twri.tamu.edu/publications/reports/2018/tr-511/

**Schramm, M.P.**, Entwistle, C., Berthold, T. 2018. Lavaca River Watershed Protection Plan. Technical report, Texas Water Resources Institute TR-507. College Station, TX. URL: http://twri.tamu.edu/publications/reports/2018/tr-507/

**Schramm, M.P.**, Entwistle, C., Berthold, T. 2017. Tres Palacios Watershed Protection Plan. Technical report, Texas Water Resources Institute TR-500. College Station, TX. URL: http://twri.tamu.edu/publications/reports/2017/tr-500/

**Schramm, M.P.**, Entwistle, C., Berthold, T. 2017. Implementation Plan for One Total Maximum Daily Load for Indicator Bacteria in Tres Palacios Creek Tidal. Prepared by the Texas Water Resources Institute for the Total Maximum Daily Load Program, Texas Commission on Environmental Quality. Austin, TX. URL: https://www.tceq.texas.gov/assets/public/waterquality/tmdl/108trespalacios/108-TresPalaciosBacteria_TMDLIPlan_Comment_July05-2017.pdf

**Schramm, M.P.** 2017. Technical Support Document for Total Maximum Daily Loads for Indicator Bacteria in Aransas River Above Tidal and Poesta Creek. Prepared by the Texas Water Resources Institute for the Total Maximum Daily Load Program, Texas Commission on Environmental Quality. Austin, TX. URL: https://www.tceq.texas.gov/assets/public/waterquality/tmdl/76copano/76-aransas-poesta-tsd.pdf

McManamay, R.A., Troia, M.J., DeRolph, C.R., Bevelhimer, M.S., **Schramm, M.P.**, Larson, K.B., Tagestad, J.D., Johnson, G.E., Jager, H.I. 2015. Identifying Environmental Opportunities outside the Hydropower Project Boundary : An Updated Methodology of the Basin Scale Opportunity Assessment. doi:10.13140/RG.2.1.3000.0482

Kramer, C., Dsouza, C., **Schramm, M.P.**, Griffin, M., Teron, L. 2014. Brownfields: From Redevelopment to Revitalization. Technical Report, Center for Energy and Environmental Policy, Newark, DE. doi:10.13140/RG.2.1.5006.0565

Caldwell, J., Cruz-Ortiz, C., Dsouza, C., Johnson, T., Schorse, M., **Schramm, M.P.**, and Zhang, X. 2012. Supporting Urban Green Infrastructure. Technical report, Center for Energy and Environmental Policy, Newark. doi:10.13140/RG.2.1.1204.9687

## Software

**Schramm, M.P.** 2018. `echor`: Access EPA ECHO Data. *R package version 0.1.2 (CRAN).* https://CRAN.R-project.org/package=echor

**Schramm, M.P.** 2018. `tbrf`: Time-Based Rolling Functions. *R package version 0.1.2 (CRAN)* https://CRAN.R-project.org/package=tbrf

## Datasets

Bevelhimer, M.S., **Schramm, M.P.** , DeRolph, C.R. 2015. Non-Federal Hydropower Mitigation Database, Oak Ridge National Laboratory, available at: http://nhaap.ornl.gov/environmental-mitigation

Bevelhimer, M.S., **Schramm M.P.**, DeRolph, C.R. 2015. US Maps of Non-Federal Hydropower Mitigation Data, Oak Ridge National Laboratory, available at: http://nhaap.ornl.gov/environmental-mitigation

Bevelhimer, M.S., **Schramm M.P.**, DeRolph, C.R. 2015. US Maps of Non-Federal Hydropower Water Quality Requirements, Oak Ridge National Laboratory, available at: http://nhaap.ornl.gov/environmental-mitigation

## Forthcoming

**Schramm, M.**, Jha, A. (forthcoming). Technical Support Document for Four Total Maximum Daily Loads for Indicator Bacteria in Neches River Tidal . Prepared by the Texas Water Resources Institute for the Total Maximum Daily Load Program, Texas Commission on Environmental Quality. Austin, TX. 

**Schramm, M.**, Jha, A. (forthcoming). Technical Support Document for One Total Maximum Daily Load for Indicator Bacteria in Hillebrandt Bayou. Prepared by the Texas Water Resources Institute for the Total Maximum Daily Load Program, Texas Commission on Environmental Quality. Austin, TX. 

**Schramm, M.**, Jha, A. (forthcoming). Technical Support Document for Two Total Maximum Daily Loads for Indicator Bacteria in Sandy Creek and Wolf Creek. Prepared by the Texas Water Resources Institute for the Total Maximum Daily Load Program, Texas Commission on Environmental Quality. Austin, TX. 

## Grants

*Texas Commision on Environmental Quality*: Basins approach to address bacterial impairments in the Lower Neches Basin (FY19); PI: Lucas Gregory. Project Lead: Michael Schramm. September 2018-August 2019. Total: \$139,343. Amount to Schramm: \$139,343.

*Texas Commision on Environmental Quality*: Basins approach to address bacterial impairments in basins 15, 16, 17 (FY19); PI: Allen Berthold. Project Lead: Michael Schramm. September 2018-August 2019. Total: \$97,399. Amount to Schramm: \$97,399.

*Texas Commision on Environmental Quality*: Lavaca River Watershed Protection Plan (WPP) - Coordination, implementation and routine water quality; PI: Allen Berthold. Project Lead: Michael Schramm. September 2018 - August 2021. Total: \$150,000. Amount to Schramm: \$124,910.

*Texas Commision on Environmental Quality*: Tres Palacios on-site sewage facilities remediation; PI: Allen Berthold. Project Lead: Michael Schramm. May 2018 - December 2020. Total: \$327,361. Amount to Schramm: \$327,361.

*Texas Commision on Environmental Quality*: Tres Palacios WPP implementation (TCEQ FY17); PI: Allen Berthold. Project Lead: Michael Schramm. May 2018 - December 2020. Total: \$355,800. Amount to Schramm: \$235,866.

*Texas General Land Office*: Mission and Aransas Rivers TMDL I-Plan implementation; PI: Allen Berthold. Project Lead: Michael Schramm. October 2017-March 2019. Total: \$83,979. Amount to Schramm: \$83,979.

*Texas General Land Office*: Coordinating implementation of the Tres Palacios Watershed Protection Plan; PI: Allen Berthold. Project Lead: Michael Schramm. October 2017-March 2019. Total: \$95,816. Amount to Schramm: \$95,816.

*Texas Commision on Environmental Quality*: Basins approach to address bacterial impairments in basins 15, 16, 17 (FY18); PI: Allen Berthold. Project Lead: Michael Schramm. September 2017-August 2018. Total: \$220,166. Amount to Schramm: \$179,996.

*Texas Commision on Environmental Quality*: Basins approach to address bacterial impairments in basins 15, 16, 17 (FY17); PI: Allen Berthold. Project Lead: Michael Schramm. September 2016-August 2017. Total: \$292,699. Amount to Schramm: \$229,649.

# Media Coverage of Projects

**Water Quality Projects**

"Experts gather to discuss Arenosa Creek's water quality": Victoria Advocate. [Link here](https://www.victoriaadvocate.com/news/agriculture/experts-gather-to-discuss-arenosa-creek-s-water-quality/article_15aea768-a18c-11e8-80e4-f320cf54cbe6.html)

"Group finalizes watershed protection plan": Victoria Advocate. [Link here](https://www.victoriaadvocate.com/counties/jackson/group-finalizes-watershed-protection-plan/article_3b443b45-800a-5f0c-b455-95bd629a1ef7.html)

"Residents look to improve Lavaca River quality": Victoria Advocate. [Link here](https://www.victoriaadvocate.com/news/local/residents-look-to-improve-lavaca-river-quality/article_66dfd2be-7e12-5916-9c20-9f751f78c497.html)

**Software**

"April 2018: "Top 40" New Packages: R-Studio blog.[Link here](https://rviews.rstudio.com/2018/05/24/april-2018-top-40-new-packages/)
