---
title: "CV"
author: "Michael Schramm"
email: mpschramm@gmail.com
output:
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
  html_document:
    df_print: paged
  word_document: default
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
geometry: margin=1in
linkcolor: blue
fontawesome: yes
phone: 910 232-3760
address: 578 John Kimbrough Blvd · 2260 TAMU · College Station, TX 77843
updated: no
urlcolor: blue
---


# Employment

*Texas Water Resources Institute, Texas A & M University*

Research Associate \hfill 2016-Current

*Oak Ridge National Laboratory, Oak Ridge, TN*

Research Associate \hfill 2014-2016

*Center for Energy and Environmental Policy, University of Delaware*

Research Assistant \hfill 2012-2013

# Education

*University of Delaware*, Master of Energy and Environmental Policy, 2013

*University of North Carolina - Wilmington*, B.A. Environmetal Studies, 2011

*University of North Carolina - Wilmington*, B.S. Biology, 2004

# Skills

GIS, `Python`, `R`, Environmental and Water Policy Analysis, Qualitative and Quantitative Data Analysis, Technical Writing, Water Quality Assessment and Modeling, Stakeholder Planning and Facilitation

# Relevant Project Experience

2016 - Current: *Addressing Bacteria Impairements in the Matagorda Basins.* TCEQ sponsored project to engage stakeholders, gather water quality data, modeling data, and develop watershed protection plans to improve water quality.

2014-2016: *Hydropower Mitigation at FERC Licensed Facilities.* Department of Energy sponsored project to develop a database of environmental and recreation mitigation requirements at non-federal hydropower facilities to assist with optimization scenarios and reduce regulatory uncertainty.

2011-2013: *Science, Energy, and Technology Policy Analysis.* Delaware General Assembly sponsored projects to develop policy analysis and case studies to improve implementation of various best practices affecting stormwater, water quality, and human health in Delaware. 



# Publications

## Journal Articles

**Schramm, M.P.**, Bevelhimer, M.S., Scherelis, C. 2017. Effects of hydrokinetic turbine sound on the behavior of four species of fish within an experimental mesocosm. *Fisheries Research* 190:1-14.

DeRolph, C.R., **Schramm, M.P.**, Bevelhimer, M.S. 2016. Predicting environmental mitigation requirements for hydropower projects through the integration of biophysical and socio-political geographies. *Science of The Total Environment* 566:888-918. doi:10.1016/j.scitotenv.2016.05.099

**Schramm, M.P.**, Bevelhimer, M.P., DeRolph, C.R. 2016. A synthesis of environmental and recreational mitigation requirements at hydropower projects in the United States. *Environmental Science & Policy* 61:87-96. doi:10.1016/j.envsci.2016.03.019

Pracheil, B.M., DeRolph C.R., **Schramm, M.P.**, Bevelhimer, M.S. 2016. A fish-eye view of riverine hydropower systems: the current understanding of the biological response to turbine passage. *Reviews in Fish Biology and Fisheries* 26(2):153-167. doi:10.1007/s11160-015-9416-8

Cutting, R.H., Cahoon, L.B., Flood, J.F., Horton, L., **Schramm, M.P.** 2010. Spill the beans: GoodGuide, Walmart and EPA use information as efficient, market-based environmental regulation. *Tul. Envtl. LJ* 24:291.

## Other Publications

**Schramm, M.P.**, Entwistle, C., Berthold, T. 2017. Implementation Plan for One Total Maximum Daily Load for Indicator Bacteria in Tres Palacios Creek Tidal. Prepared by Texas Water Resources Institute for Total Maximum Daily Load Program, Texas Commission on Environmental Quality. Austin, TX. URL: https://www.tceq.texas.gov/assets/public/waterquality/tmdl/108trespalacios/108-TresPalaciosBacteria_TMDLIPlan_Comment_July05-2017.pdf

**Schramm, M.P.** 2017. Technical Support Document for Total Maximum Daily Loads for Indicator Bacteria in Aransas River Above Tidal and Poesta Creek. Prepared by Texas Water Resources Institute for Total Maximum Daily Load Program, Texas Commission on Environmental Quality. Austin, TX. URL: https://www.tceq.texas.gov/assets/public/waterquality/tmdl/76copano/76-aransas-poesta-tsd.pdf

McManamay, R.A., Troia, M.J., DeRolph, C.R., Bevelhimer, M.S., **Schramm, M.P.**, Larson, K.B., Tagestad, J.D., Johnson, G.E., Jager, H.I. 2015. Identifying Environmental Opportunities outside the Hydropower Project Boundary : An Updated Methodology of the Basin Scale Opportunity Assessment. doi:10.13140/RG.2.1.3000.0482

Kramer, C., Dsouza, C., **Schramm, M.P.**, Griffin, M., Teron, L. 2014. Brownfields: From Redevelopment to Revitalization. Technical Report, Center for Energy and Environmental Policy, Newark, DE. doi:10.13140/RG.2.1.5006.0565

Caldwell, J., Cruz-Ortiz, C., Dsouza, C., Johnson, T., Schorse, M., **Schramm, M.P.**, and Zhang, X. 2012. Supporting Urban Green Infrastructure. Technical report, Center for Energy and Environmental Policy, Newark. doi:10.13140/RG.2.1.1204.9687

## Forthcoming

**Schramm, M.P.**, Entwistle, C., Berthold, T. (Forthcoming). Lavaca River Watershed Protection Plan. Technical report, Texas Water Resources Institute. College Station, TX.

**Schramm, M.P.**, Entwistle, C., Berthold, T.A. (Forthcoming). Tres Palacios Watershed Protection Plan. Technical report, Texas Water Resources Institute TR-500. College Station, TX.

**Schramm, M.P.**, Entwistle, C., Berthold, T. (Forthcoming). Implementation Plan for Two Total Maximum Daily Loads for Indicator Bacteria in Lavaca River Above Tidal and Rocky Creek. Prepared by Texas Water Resources Institute for Total Maximum Daily Load Program, Texas Commission on Environmental Quality. Austin, TX.

